import fs from "fs";
import type {
  DefaultEnvironment,
  ServerConfigFactory,
  ServerConfig,
  ServerWebAppManifest,
} from "../types.js";
import { buildSync as esbuild } from "esbuild";
import { dirname } from "path";
import { fileURLToPath } from "url";
import { defaultProductionConfig } from "../constants.js";

let config: ServerConfig = {};
if (fs.existsSync("michi.config.ts")) {
  esbuild({
    bundle: true,
    entryPoints: [
      {
        in: "michi.config.ts",
        out: "michi.config",
      },
    ],
    external: ["esbuild"],
    outExtension: { ".js": ".cjs" },
    outdir: dirname(fileURLToPath(import.meta.url)),
    format: "cjs",
    platform: "node",
    logLevel: "error",
    target: ["node16"],
  });
  // The path is constructed dynamically so the bundler doesn't try to resolve
  // it at build time — the file is generated by esbuild a few lines above and
  // only exists at runtime.
  const cjsPath = `./${"michi.config"}.cjs`;
  const imported = await import(cjsPath);
  const configFactory: ServerConfigFactory =
    imported.default?.default || imported.default || imported; // fallback if Bun unwraps differently

  config = configFactory({
    ...defaultProductionConfig,
    environment: process.env.NODE_ENV as DefaultEnvironment,
  });
  const options = config.public?.manifest ?? {};
  if ("file_handlers" in options)
    (options as ServerWebAppManifest)?.file_handlers?.forEach((fileHandler) => {
      Object.entries(fileHandler.accept).forEach(([name, value]) => {
        fileHandler.accept[name] = Array.from(value);
      });
    });
}
export const userConfig = config;
